Repository arkedge/c2a-core, pull requests merged in 2023-07, with the labels that each got.

#1 v4 fork に伴う README，Licence の修正
  Docs/Img/arkedgespace_logo.png
  LICENSE
  README.md
Labels: documentation, priority::high

#3 Update template
  .github/ISSUE_TEMPLATE/action_item.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, priority::high

#16 Docs の中でコードを参照している URL の行数を修正
  Docs/Core/communication.md
  Docs/Driver/communication_with_components.md
Labels: documentation

#19 App の initializer, entry_point の返り値を void から RESULT にする
  Applications/divided_cmd_utility.c
  Applications/event_utility.c
  Applications/gs_command_dispatcher.c
  Applications/memory_dump.c
  Applications/nop.c
  Applications/realtime_command_dispatcher.c
  Applications/telemetry_manager.c
  Applications/timeline_command_dispatcher.c
  Applications/utility_command.c
  Applications/utility_counter.c
  Examples/mobc/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/mobc/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/mobc/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/mobc/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/subobc/src/src_user/Applications/DriverInstances/di_mobc.c
  Examples/subobc/src/src_user/Applications/UserDefined/debug_apps.c
  System/ApplicationManager/app_info.c
  System/ApplicationManager/app_info.h
  System/ApplicationManager/app_manager.c
  System/ApplicationManager/app_manager.h
Labels: enhancement

#20 Change dir name coding rule to snake_case
  Docs/General/coding_rule.md
Labels: documentation, enhancement, priority::high

#21 Rename component: IfWrapper -> hal
  Applications/utility_command.c
  Applications/utility_command.h
  CMakeLists.txt
  Docs/General/coding_rule.md
  Drivers/Super/driver_super.h
  Script/AddSection/settings.pl
  Script/CI/check_encoding.json
  Script/migration/v4-rename-ifwrapper.sh
  System/WatchdogTimer/watchdog_timer.c
  System/WatchdogTimer/watchdog_timer.h
  hal/aa.h
  hal/ccsds.h
  hal/dc.h
  hal/i2c.h
  hal/i2c_common.c
  hal/i2c_common.h
  hal/pa.h
  hal/spi.h
  hal/spwire.h
  hal/uart.h
  hal/wdt.h
Labels: documentation, enhancement, priority::high, tools

#24 Apply rename migration to example users: IfWrapper -> hal
  Examples/mobc/CMakeLists.txt
  Examples/mobc/src/src_user/Drivers/Aocs/aobc.h
  Examples/mobc/src/src_user/Drivers/Com/gs.c
  Examples/mobc/src/src_user/Drivers/Com/gs.h
  Examples/mobc/src/src_user/Drivers/Etc/uart_test.h
  Examples/mobc/src/src_user/Script/AddSection/settings.pl
  Examples/mobc/src/src_user/hal/CMakeLists.txt
  Examples/mobc/src/src_user/hal/ccsds_user.h
  Examples/mobc/src/src_user/hal/common/.gitkeep
  Examples/mobc/src/src_user/hal/if_list.c
  Examples/mobc/src/src_user/hal/if_list.h
  Examples/mobc/src/src_user/hal/sils/ccsds_sils.cpp
  Examples/mobc/src/src_user/hal/sils/ccsds_sils_sci_if.cpp
  Examples/mobc/src/src_user/hal/sils/ccsds_sils_sci_if.hpp
  Examples/mobc/src/src_user/hal/sils/i2c_sils.cpp
  Examples/mobc/src/src_user/hal/sils/uart_sils.cpp
  Examples/mobc/src/src_user/hal/sils/uart_sils_sci_if.cpp
  Examples/mobc/src/src_user/hal/sils/uart_sils_sci_if.hpp
  Examples/mobc/src/src_user/hal/sils/wdt_sils.cpp
  Examples/mobc/src/src_user/hal/sils_mockup/README.md
  Examples/mobc/src/src_user/hal/sils_mockup/ccsds_sils.c
  Examples/mobc/src/src_user/hal/sils_mockup/i2c_sils.c
  Examples/mobc/src/src_user/hal/sils_mockup/uart_sils.c
  Examples/mobc/src/src_user/hal/sils_mockup/wdt_sils.c
  Examples/subobc/CMakeLists.txt
  Examples/subobc/src/src_user/Drivers/Etc/mobc.h
  Examples/subobc/src/src_user/Script/AddSection/settings.pl
  Examples/subobc/src/src_user/hal/CMakeLists.txt
  Examples/subobc/src/src_user/hal/common/.gitkeep
  Examples/subobc/src/src_user/hal/if_list.c
  Examples/subobc/src/src_user/hal/if_list.h
  Examples/subobc/src/src_user/hal/sils/i2c_sils.cpp
  Examples/subobc/src/src_user/hal/sils/uart_sils.cpp
  Examples/subobc/src/src_user/hal/sils/uart_sils_sci_if.cpp
  Examples/subobc/src/src_user/hal/sils/uart_sils_sci_if.hpp
  Examples/subobc/src/src_user/hal/sils/wdt_sils.cpp
  Examples/subobc/src/src_user/hal/sils_mockup/README.md
  Examples/subobc/src/src_user/hal/sils_mockup/i2c_sils.c
  Examples/subobc/src/src_user/hal/sils_mockup/uart_sils.c
  Examples/subobc/src/src_user/hal/sils_mockup/wdt_sils.c
  Examples/subobc/sync_with_mobc_example.bat
Labels: enhancement, priority::high, tools

#25 Remove old HAL for DC
  hal/dc.h
Labels: priority::high

#29 Update repository URL in Rust package due to fork
  Cargo.toml
Labels: documentation, enhancement

#27 エンコーディングチェック CI に subobc が抜けていたので追加
  Script/CI/check_encoding.json
Labels: priority::medium

#30 Move c2a-core crate source file to top dir for avoid misleading
  Cargo.toml
  c2a_core.rs
Labels: enhancement, tools
