Repository arkedge/c2a-core, pull requests merged in 2023-12, with the labels that each got.

#219 CCSDS data link layer における SCID をユーザー設定として切り出す
  CHANGELOG.md
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs_validate.c
  examples/mobc/src/src_user/settings/CMakeLists.txt
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/aos_transfer_frame_define.c
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/aos_transfer_frame_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/tc_transfer_frame_define.c
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/tc_transfer_frame_define.h
  tlm_cmd/ccsds/aos_space_data_link_protocol/aos_transfer_frame.c
  tlm_cmd/ccsds/aos_space_data_link_protocol/aos_transfer_frame.h
  tlm_cmd/ccsds/tc_space_data_link_protocol/tc_transfer_frame.c
  tlm_cmd/ccsds/tc_space_data_link_protocol/tc_transfer_frame.h
Labels: enhancement, priority::high

#220 APIDの命名規則の更新
  CHANGELOG.md
  docs/core/communication.md
  examples/mobc/src/src_user/component_driver/com/gs_validate.c
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.c
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/common_cmd_packet_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.h
  examples/mobc/src/src_user/tlm_cmd/normal_block_command_definition/nbc_test_bcl.c
  examples/mobc/src/src_user/tlm_cmd/user_packet_handler.c
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.c
  examples/subobc/src/src_user/component_driver/etc/mobc.c
  examples/subobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.c
  examples/subobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.h
  examples/subobc/src/src_user/settings/tlm_cmd/common_cmd_packet_define.h
  examples/subobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.h
  examples/subobc/src/src_user/test/test_comm_between_c2a.py
  tlm_cmd/ccsds/space_packet_protocol/cmd_space_packet.c
  tlm_cmd/common_cmd_packet.h
  tlm_cmd/common_tlm_cmd_packet.h
  tlm_cmd/common_tlm_packet.h
  tlm_cmd/packet_handler.c
  tlm_cmd/telemetry_generator.c
Labels: priority::medium

#236 [stable-4.0] backport PL_BC_LIST_CLEARED を level high で EL 登録する
  applications/timeline_command_dispatcher.c
Labels: priority::medium

#240 [code-generator] 自動生成コードの @note に，生成元DBのコミットハッシュと生成パラメータを出力する
  .github/workflows/check_code_generation.yml
  CHANGELOG.md
  code-generator/README.md
  code-generator/my_mod/cmd_def.py
  code-generator/my_mod/tlm_buffer.py
  code-generator/my_mod/tlm_def.py
  code-generator/my_mod/util.py
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/subobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/subobc/src/src_user/tlm_cmd/command_definitions.c
  examples/subobc/src/src_user/tlm_cmd/command_definitions.h
  examples/subobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/subobc/src/src_user/tlm_cmd/telemetry_definitions.h
Labels: documentation, priority::medium, tools

#243 [code-generator] max_tlm_num のアサーションを追加
  CHANGELOG.md
  code-generator/my_mod/load_db.py
Labels: enhancement, tools

#245 MEM DUMP を整備する
  CHANGELOG.md
  applications/memory_dump.c
  applications/memory_dump.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
  examples/mobc/src/src_user/settings/applications/memory_dump_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_MEM.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MEM.csv
Labels: enhancement, priority::high

#246 node_modules を .gitignore に追加
  .gitignore
  CHANGELOG.md
Labels: priority::medium

#237 [stable-4.0] Update version (v4.0.2)
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
Labels: priority::medium

#238 Add missing v4.1.0 compatible tools to changelog
  CHANGELOG.md
Labels: documentation, priority::high

#251 Refactor code-generator
  .github/workflows/check_code_generation.yml
  CHANGELOG.md
  code-generator/my_mod/util.py
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/subobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/subobc/src/src_user/tlm_cmd/command_definitions.c
  examples/subobc/src/src_user/tlm_cmd/command_definitions.h
  examples/subobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/subobc/src/src_user/tlm_cmd/telemetry_definitions.h
Labels: priority::high, tools

#133 sils-runtime: require c2a-core v4
  sils-runtime/Cargo.toml
Labels: enhancement

#134 c2a-core hal crates: require c2a-core v4
  hal/i2c-noop/Cargo.toml
  hal/spi-noop/Cargo.toml
  hal/uart-kble/Cargo.toml
  hal/uart-noop/Cargo.toml
  hal/wdt-noop/Cargo.toml
Labels: enhancement

#247 VS Code を使ったデバッグ手順の追加 / READMEの微修正
  .vscode/launch.json
  CHANGELOG.md
  README.md
  docs/sils/c2a_sils_runtime.md
  examples/mobc/package.json
Labels: documentation, enhancement, priority::high

#249 .nvmrc の追加
  CHANGELOG.md
  docs/sils/c2a_sils_runtime.md
  examples/mobc/.nvmrc
  examples/subobc/.nvmrc
Labels: documentation, priority::high, tools

#256 [code-generator] MOBC が定義を持っていない Sub OBC の tlm id の tlm でも GS に Forward できるように
  CHANGELOG.md
  code-generator/my_mod/tlm_buffer.py
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
Labels: enhancement, priority::medium, tools

#258 Update renovate default reviewers
  renovate.json
Labels: priority::medium, tools

#261 TL TLM に TL に登録された cmd 数を追加
  CHANGELOG.md
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
Labels: enhancement, priority::medium
