Repository arkedge/c2a-core, pull requests merged in 2023-08, with the labels that each got.

#31 Rename docs dir to snake case
  README.md
  Script/CI/check_coding_rule.json
  TlmCmd/Ccsds/space_packet.h
  TlmCmd/common_cmd_packet.h
  c2a_core_main.h
  docs/README.md
  docs/application/overview.md
  docs/core/communication.md
  docs/core/tips.md
  docs/driver/communication_with_components.md
  docs/driver/overview.md
  docs/general/coding_acronyms.md
  docs/general/coding_rule.md
  docs/general/overview.md
  docs/general/release.md
  docs/sils/s2e_integration.md
  docs/tips/parameter_settings.md
  docs/tools/overview.md
  examples/mobc/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  examples/subobc/README.md
  examples/subobc/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
Labels: documentation, enhancement

#34 Make c2a-core repository as cargo workspace
  Cargo.toml
  docs/general/release.md
Labels: enhancement, tools

#36 Add rustfmt check
  .github/workflows/rust.yml
  build.rs
Labels: enhancement, tools

#37 Extern System functions for SILS runtime
  System/mod.rs
  c2a_core.rs
Labels: enhancement, priority::high, tools

#42 Update directory name rule for Rust crate
  docs/general/coding_rule.md
Labels: documentation, enhancement, priority::high, tools

#38 Introduce c2a-sils-runtime
  Cargo.toml
  sils-runtime/Cargo.toml
  sils-runtime/src/lib.rs
Labels: enhancement, priority::high, tools

#40 Add HAL noop implementation
  Cargo.toml
  hal/i2c-noop/Cargo.toml
  hal/i2c-noop/src/lib.rs
  hal/spi-noop/Cargo.toml
  hal/spi-noop/src/lib.rs
  hal/uart-noop/Cargo.toml
  hal/uart-noop/src/lib.rs
  hal/wdt-noop/Cargo.toml
  hal/wdt-noop/src/lib.rs
Labels: enhancement, priority::high, tools

#41 Add kble-based c2a-hal UART emulation
  Cargo.toml
  hal/uart-kble/Cargo.toml
  hal/uart-kble/src/buffer.rs
  hal/uart-kble/src/kble.rs
  hal/uart-kble/src/lib.rs
Labels: enhancement, priority::high, tools

#33 Rename script dir to snake case
  .github/workflows/check_coding_rule.yml
  .github/workflows/check_encoding.yml
  Library/git_revision.h
  script/add_section/AddSection.pl
  script/add_section/log.log
  script/add_section/settings.pl
  script/add_section/utils.pl
  script/ci/check_coding_rule.json
  script/ci/check_coding_rule.py
  script/ci/check_encoding.json
  script/ci/check_encoding.py
  script/ci/remove_duplicate_error.py
  script/git/revision.bat
  script/git/revision.sh
  script/git_hooks/pre-commit
  script/migration/v4-rename-ifwrapper.sh
  script/migration/v4-rename-script.sh
  setup.bat
  setup.sh
Labels: enhancement, tools

#44 Run examples/subobc on c2a-sils-runtime
  Cargo.toml
  examples/subobc/Cargo.toml
  examples/subobc/build.rs
  examples/subobc/src/main.rs
Labels: enhancement, priority::high, tools

#45 Run examples/mobc on c2a-sils-runtime
  Cargo.toml
  examples/mobc/Cargo.toml
  examples/mobc/build.rs
  examples/mobc/src/main.rs
  examples/mobc/src/src_user/hal/ccsds-kble/Cargo.toml
  examples/mobc/src/src_user/hal/ccsds-kble/build.rs
  examples/mobc/src/src_user/hal/ccsds-kble/src/ccsds_user.rs
  examples/mobc/src/src_user/hal/ccsds-kble/src/ccsds_user_bind.rs
  examples/mobc/src/src_user/hal/ccsds-kble/src/kble.rs
  examples/mobc/src/src_user/hal/ccsds-kble/src/lib.rs
Labels: enhancement, priority::high, tools

#46 Rename Applications dir to snake case
  CMakeLists.txt
  System/ApplicationManager/app_manager.c
  System/EventManager/event_handler.c
  System/ModeManager/mode_manager.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/packet_handler.h
  applications/CMakeLists.txt
  applications/divided_cmd_utility.c
  applications/divided_cmd_utility.h
  applications/event_utility.c
  applications/event_utility.h
  applications/gs_command_dispatcher.c
  applications/gs_command_dispatcher.h
  applications/memory_dump.c
  applications/memory_dump.h
  applications/nop.c
  applications/nop.h
  applications/realtime_command_dispatcher.c
  applications/realtime_command_dispatcher.h
  applications/telemetry_manager.c
  applications/telemetry_manager.h
  applications/test_app/CMakeLists.txt
  applications/test_app/test_ccp_util.c
  applications/test_app/test_ccp_util.h
  applications/timeline_command_dispatcher.c
  applications/timeline_command_dispatcher.h
  applications/timeline_command_dispatcher_id_define.h
  applications/utility_command.c
  applications/utility_command.h
  applications/utility_counter.c
  applications/utility_counter.h
  c2a_core_main.c
  docs/general/coding_rule.md
  script/add_section/settings.pl
  script/ci/check_encoding.json
  script/migration/v4-rename-applications.sh
Labels: enhancement

#51 Apply rename migration to example users: Library -> library
  examples/mobc/CMakeLists.txt
  examples/mobc/src/src_user/Drivers/Etc/uart_test.c
  examples/mobc/src/src_user/Settings/git_revision_config.h
  examples/mobc/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.c
  examples/mobc/src/src_user/TlmCmd/telemetry_source.h
  examples/mobc/src/src_user/applications/driver_instances/di_aobc.c
  examples/mobc/src/src_user/applications/driver_instances/di_gs.c
  examples/mobc/src/src_user/applications/driver_instances/di_uart_test.c
  examples/mobc/src/src_user/applications/user_defined/debug_apps.c
  examples/mobc/src/src_user/c2a_main.c
  examples/mobc/src/src_user/library/CMakeLists.txt
  examples/mobc/src/src_user/library/print.c
  examples/mobc/src/src_user/library/vt100.c
  examples/mobc/src/src_user/library/vt100.h
  examples/mobc/src/src_user/script/add_section/settings.pl
  examples/subobc/CMakeLists.txt
  examples/subobc/src/src_user/Settings/git_revision_config.h
  examples/subobc/src/src_user/TlmCmd/telemetry_source.h
  examples/subobc/src/src_user/applications/driver_instances/di_mobc.c
  examples/subobc/src/src_user/applications/user_defined/debug_apps.c
  examples/subobc/src/src_user/c2a_main.c
  examples/subobc/src/src_user/library/CMakeLists.txt
  examples/subobc/src/src_user/library/print.c
  examples/subobc/src/src_user/library/vt100.c
  examples/subobc/src/src_user/library/vt100.h
  examples/subobc/src/src_user/script/add_section/settings.pl
  examples/subobc/sync_with_mobc_example.bat
Labels: enhancement

#52 Update README about SILS runtime
  README.md
Labels: documentation

#53 Fix missing Library rename in cargo config
  Cargo.toml
Labels: bug, priority::high, tools

#57 Run Rust CI on develop
  .github/workflows/rust.yml
Labels: bug, priority::high, tools

#56 Introduce C2A Boom to example users
  .gitignore
  examples/mobc/package-lock.json
  examples/mobc/package.json
  examples/mobc/satconfig.json
  examples/mobc/spaghetti.jsonnet
  examples/mobc/spaghetti.subobc.jsonnet
  examples/mobc/tools/.gitignore
  examples/mobc/tools/install.sh
  examples/mobc/tools/package.json
  examples/subobc/package-lock.json
  examples/subobc/package.json
  examples/subobc/satconfig.json
  examples/subobc/spaghetti.jsonnet
  examples/subobc/tools/.gitignore
  examples/subobc/tools/install.sh
  examples/subobc/tools/package.json
Labels: enhancement, priority::high, tools

#59 Introduce Gaia pytest
  examples/mobc/src/src_user/Test/.python-version
  examples/mobc/src/src_user/Test/README.md
  examples/mobc/src/src_user/Test/pyproject.toml
  examples/mobc/src/src_user/Test/requirements-dev.lock
  examples/mobc/src/src_user/Test/requirements.lock
  examples/mobc/src/src_user/Test/utils/wings_utils.py
  examples/subobc/src/src_user/Test/.python-version
  examples/subobc/src/src_user/Test/README.md
  examples/subobc/src/src_user/Test/pyproject.toml
  examples/subobc/src/src_user/Test/requirements-dev.lock
  examples/subobc/src/src_user/Test/requirements.lock
  examples/subobc/src/src_user/Test/utils/wings_utils.py
Labels: enhancement, priority::high, tools

#62 関連リポジトリをreadmeに追加
  README.md
Labels: documentation

#60 Add Gaia pytest CI
  .github/workflows/pytest.yml
  examples/mobc/package.json
Labels: enhancement, priority::high, tools

#63 Pre Release (v4.0.0-beta.0): v4 の最初の beta release
  Cargo.toml
  c2a_core_main.h
  library/bind-utils/Cargo.toml
Labels: enhancement, priority::high, tools

#65 通信プロトコルについてのドキュメントを更新
  docs/core/communication.md
  docs/driver/communication_with_components.md
Labels: documentation, priority::high

#67 Renovate specified version in GitHub Actions workflow
  .github/workflows/build_with_s2e.yml
  renovate.json
Labels: enhancement, priority::high, tools, S2E

#69 Remove Renovate regexManager match v prefix
  renovate.json
Labels: bug, priority::high, tools, S2E

#54 Rename System dir to snake case
  CMakeLists.txt
  Drivers/Super/driver_super.h
  TlmCmd/block_command_executor.c
  TlmCmd/block_command_loader.h
  TlmCmd/block_command_table.c
  TlmCmd/command_analyze.c
  TlmCmd/command_dispatcher.c
  TlmCmd/command_dispatcher.h
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_tlm_packet.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_list.c
  TlmCmd/telemetry_generator.c
  applications/divided_cmd_utility.c
  applications/divided_cmd_utility.h
  applications/event_utility.c
  applications/event_utility.h
  applications/gs_command_dispatcher.h
  applications/memory_dump.c
  applications/memory_dump.h
  applications/nop.h
  applications/realtime_command_dispatcher.h
  applications/telemetry_manager.h
  applications/timeline_command_dispatcher.c
  applications/timeline_command_dispatcher.h
  applications/utility_command.c
  applications/utility_command.h
  applications/utility_counter.h
  build.rs
  c2a_core.rs
  c2a_core_main.c
  docs/tips/parameter_settings.md
  script/migration/v4-rename-system.sh
  sils-runtime/src/lib.rs
  system/application_manager/app_info.c
  system/application_manager/app_info.h
  system/application_manager/app_manager.c
  system/application_manager/app_manager.h
  system/event_manager/event_handler.c
  system/event_manager/event_handler.h
  system/event_manager/event_logger.c
  system/event_manager/event_logger.h
  system/event_manager/event_manager.c
  system/event_manager/event_manager.h
  system/mod.rs
  system/mode_manager/mode_manager.c
  system/mode_manager/mode_manager.h
  system/task_manager/task_dispatcher.c
  system/task_manager/task_dispatcher.h
  system/time_manager/obc_time.c
  system/time_manager/obc_time.h
  system/time_manager/obc_time_config.h
  system/time_manager/time_manager.c
  system/time_manager/time_manager.h
  system/watchdog_timer/watchdog_timer.c
  system/watchdog_timer/watchdog_timer.h
Labels: enhancement, priority::high

#55 Apply rename migration to example users: System -> system
  .github/workflows/pytest.yml
  examples/mobc/src/s2e_mockup/main.cpp
  examples/mobc/src/src_user/Drivers/Aocs/aobc.h
  examples/mobc/src/src_user/Settings/CMakeLists.txt
  examples/mobc/src/src_user/Settings/Modes/Transitions/sl_initial.c
  examples/mobc/src/src_user/Settings/Modes/Transitions/sl_nop.c
  examples/mobc/src/src_user/Settings/Modes/mode_definitions.c
  examples/mobc/src/src_user/Settings/system/app_manager_params.h
  examples/mobc/src/src_user/Settings/system/event_handler_params.h
  examples/mobc/src/src_user/Settings/system/event_handler_rules/event_handler_rule_test.c
  examples/mobc/src/src_user/Settings/system/event_handler_rules/event_handler_rules.c
  examples/mobc/src/src_user/Settings/system/event_handler_rules/event_handler_rules.h
  examples/mobc/src/src_user/Settings/system/event_logger_group.h
  examples/mobc/src/src_user/Settings/system/event_logger_params.h
  examples/mobc/src/src_user/Settings/system/event_logger_settings.c
  examples/mobc/src/src_user/Settings/system/event_logger_settings.h
  examples/mobc/src/src_user/Settings/system/obc_time_params.h
  examples/mobc/src/src_user/Test/test/src_core/system/event_manager/test_event_handler.py
  examples/mobc/src/src_user/Test/test/src_core/system/event_manager/test_event_logger.py
  examples/mobc/src/src_user/Test/test/src_core/system/mode_manager/test_mode_manager.py
  examples/mobc/src/src_user/Test/test/src_core/system/task_manager/test_task_dispatcher.py
  examples/mobc/src/src_user/Test/test/src_core/system/time_manager/test_obc_time.py
  examples/mobc/src/src_user/Test/test/src_core/system/time_manager/test_time_manager.py
  examples/mobc/src/src_user/Test/test/src_core/system/watchdog_timer/test_watchdog_timer.py
  examples/mobc/src/src_user/TlmCmd/Ccsds/tcp_to_m_pdu.h
  examples/mobc/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_respond_eh_for_test.c
  examples/mobc/src/src_user/TlmCmd/command_source.h
  examples/mobc/src/src_user/TlmCmd/common_tlm_packet.c
  examples/mobc/src/src_user/TlmCmd/telemetry_source.h
  examples/mobc/src/src_user/applications/app_registry.c
  examples/mobc/src/src_user/applications/driver_instances/di_aobc.h
  examples/mobc/src/src_user/applications/driver_instances/di_gs.h
  examples/mobc/src/src_user/applications/driver_instances/di_uart_test.h
  examples/mobc/src/src_user/applications/user_defined/debug_apps.c
  examples/mobc/src/src_user/applications/user_defined/debug_apps.h
  examples/mobc/src/src_user/c2a_main.c
  examples/mobc/src/src_user/library/print.c
  examples/subobc/src/s2e_mockup/main.cpp
  examples/subobc/src/src_user/Drivers/Etc/mobc.h
  examples/subobc/src/src_user/Settings/CMakeLists.txt
  examples/subobc/src/src_user/Settings/Modes/Transitions/sl_initial.c
  examples/subobc/src/src_user/Settings/Modes/Transitions/sl_nop.c
  examples/subobc/src/src_user/Settings/Modes/mode_definitions.c
  examples/subobc/src/src_user/Settings/system/app_manager_params.h
  examples/subobc/src/src_user/Settings/system/event_handler_params.h
  examples/subobc/src/src_user/Settings/system/event_handler_rules/event_handler_rules.c
  examples/subobc/src/src_user/Settings/system/event_handler_rules/event_handler_rules.h
  examples/subobc/src/src_user/Settings/system/event_logger_group.h
  examples/subobc/src/src_user/Settings/system/event_logger_params.h
  examples/subobc/src/src_user/Settings/system/event_logger_settings.c
  examples/subobc/src/src_user/Settings/system/event_logger_settings.h
  examples/subobc/src/src_user/Settings/system/obc_time_params.h
  examples/subobc/src/src_user/TlmCmd/command_source.h
  examples/subobc/src/src_user/TlmCmd/telemetry_source.h
  examples/subobc/src/src_user/applications/app_registry.c
  examples/subobc/src/src_user/applications/driver_instances/di_mobc.h
  examples/subobc/src/src_user/applications/user_defined/debug_apps.c
  examples/subobc/src/src_user/applications/user_defined/debug_apps.h
  examples/subobc/src/src_user/c2a_main.c
  examples/subobc/src/src_user/library/print.c
Labels: enhancement, priority::high

#74 pytest の 重複を除去する
  .github/workflows/pytest.yml
Labels: bug, tools

#78 Automatically add bug label to bug report issue
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: priority::low, tools

#77 Use locked version dependencies for install jrsonnet
  examples/mobc/tools/install.sh
  examples/subobc/tools/install.sh
Labels: bug, priority::high, tools
