Repository arkedge/c2a-core, pull requests merged in 2023-09, with the labels that each got.

#85 Create CHANGELOG.md & write v4 current change log
  CHANGELOG.md
  README.md
Labels: documentation, enhancement, priority::high, tools

#93 リリースルールの明瞭化
  docs/general/release.md
Labels: documentation, priority::high

#96 Use released version tools
  CHANGELOG.md
  examples/mobc/src/src_user/Test/pyproject.toml
  examples/mobc/src/src_user/Test/requirements-dev.lock
  examples/mobc/src/src_user/Test/requirements.lock
  examples/subobc/src/src_user/Test/pyproject.toml
  examples/subobc/src/src_user/Test/requirements-dev.lock
  examples/subobc/src/src_user/Test/requirements.lock
Labels: priority::high, tools

#100 Switch rye build-system backend from hatchling to pdm
  examples/mobc/src/src_user/Test/pyproject.toml
  examples/subobc/src/src_user/Test/pyproject.toml
Labels: priority::high, tools

#94 Pre Release (v4.0.0-beta.1): メジャーバージョンアップ中のリリースルールの修正
  Cargo.toml
  c2a_core_main.h
  docs/general/release.md
Labels: documentation, priority::high

#99 Import c2a-enum-loader
  CHANGELOG.md
  README.md
  docs/general/release.md
  enum-loader/.flake8
  enum-loader/.gitignore
  enum-loader/README.md
  enum-loader/c2aenum/__init__.py
  enum-loader/c2aenum/enum_loader.py
  enum-loader/pyproject.toml
  enum-loader/setup.py
  examples/mobc/src/src_user/Test/README.md
  examples/mobc/src/src_user/Test/pyproject.toml
  examples/mobc/src/src_user/Test/requirements-dev.lock
  examples/mobc/src/src_user/Test/requirements.lock
  examples/subobc/src/src_user/Test/pyproject.toml
  examples/subobc/src/src_user/Test/requirements-dev.lock
  examples/subobc/src/src_user/Test/requirements.lock
Labels: enhancement, priority::high, tools
