Repository arkedge/c2a-core, pull requests merged in 2023-10, with the labels that each got.

#111 Import c2a-tlm-cmd-code-generator
  CHANGELOG.md
  README.md
  docs/driver/communication_with_components.md
  docs/general/release.md
  tlm-cmd-code-generator/.flake8
  tlm-cmd-code-generator/.gitignore
  tlm-cmd-code-generator/GenerateC2ACode.py
  tlm-cmd-code-generator/README.md
  tlm-cmd-code-generator/my_mod/cmd_def.py
  tlm-cmd-code-generator/my_mod/load_db.py
  tlm-cmd-code-generator/my_mod/tlm_buffer.py
  tlm-cmd-code-generator/my_mod/tlm_def.py
  tlm-cmd-code-generator/pyproject.toml
  tlm-cmd-code-generator/requirements.txt
  tlm-cmd-code-generator/settings.json
Labels: priority::high, tools

#118 Remove unneeded directory
  examples/mobc/src/src_user/BootLoader/.gitkeep
  examples/mobc/src/src_user/ReProgramming/.gitkeep
  examples/subobc/src/src_user/BootLoader/.gitkeep
  examples/subobc/src/src_user/ReProgramming/.gitkeep
Labels: invalid, priority::medium

#117 Update tlm-cmd-code-generator example settings & docs
  tlm-cmd-code-generator/README.md
  tlm-cmd-code-generator/settings_mobc.json
  tlm-cmd-code-generator/settings_subobc.json
Labels: enhancement, priority::medium, tools

#122 Refactor driver directory structure
  CMakeLists.txt
  docs/driver/overview.md
  docs/tips/parameter_settings.md
  driver/common_tlm_cmd_packet_for_driver_super.c
  driver/common_tlm_cmd_packet_for_driver_super.h
  driver/data_link_layer_definition.h
  driver/driver_super.c
  driver/driver_super.h
  driver/eb90_frame_for_driver_super.c
  driver/eb90_frame_for_driver_super.h
  driver/eb90_packet_for_driver_super.c
  driver/eb90_packet_for_driver_super.h
  enum-loader/c2aenum/enum_loader.py
  hal/i2c_common.h
  script/add_section/settings.pl
  script/ci/check_encoding.json
  script/migration/v4-rename-driver.sh
  tlm-cmd-code-generator/README.md
  tlm-cmd-code-generator/my_mod/cmd_def.py
  tlm-cmd-code-generator/my_mod/tlm_buffer.py
  tlm-cmd-code-generator/my_mod/tlm_def.py
  tlm-cmd-code-generator/settings_mobc.json
Labels: enhancement, priority::high, tools

#124 Apply direcotory refactor migration(Drivers -> driver)
  examples/mobc/CMakeLists.txt
  examples/mobc/src/src_user/Settings/Modes/Transitions/sl_initial.c
  examples/mobc/src/src_user/applications/driver_instances/di_aobc.c
  examples/mobc/src/src_user/applications/driver_instances/di_aobc.h
  examples/mobc/src/src_user/applications/driver_instances/di_gs.c
  examples/mobc/src/src_user/applications/driver_instances/di_gs.h
  examples/mobc/src/src_user/applications/driver_instances/di_uart_test.h
  examples/mobc/src/src_user/driver/CMakeLists.txt
  examples/mobc/src/src_user/driver/aocs/aobc.c
  examples/mobc/src/src_user/driver/aocs/aobc.h
  examples/mobc/src/src_user/driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/driver/aocs/aobc_telemetry_definitions.h
  examples/mobc/src/src_user/driver/cdh/.gitkeep
  examples/mobc/src/src_user/driver/com/gs.c
  examples/mobc/src/src_user/driver/com/gs.h
  examples/mobc/src/src_user/driver/com/gs_validate.c
  examples/mobc/src/src_user/driver/com/gs_validate.h
  examples/mobc/src/src_user/driver/etc/uart_test.c
  examples/mobc/src/src_user/driver/etc/uart_test.h
  examples/mobc/src/src_user/driver/mission/.gitkeep
  examples/mobc/src/src_user/driver/power/.gitkeep
  examples/mobc/src/src_user/driver/prop/.gitkeep
  examples/mobc/src/src_user/driver/thermal/.gitkeep
  examples/mobc/src/src_user/script/add_section/settings.pl
  examples/mobc/src/src_user/tlm_cmd/normal_block_command_definition/nbc_test_bcl.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_source.h
  examples/subobc/CMakeLists.txt
  examples/subobc/src/src_user/applications/driver_instances/di_mobc.h
  examples/subobc/src/src_user/driver/CMakeLists.txt
  examples/subobc/src/src_user/driver/etc/mobc.c
  examples/subobc/src/src_user/driver/etc/mobc.h
  examples/subobc/src/src_user/script/add_section/settings.pl
Labels: enhancement, priority::high

#126 Add example user's tlm_cmd code generation check workflow
  .github/workflows/check_code_generation.yml
  tlm-cmd-code-generator/.gitignore
Labels: enhancement, tools

#125 Fix missing system rename
  applications/utility_counter.c
  applications/utility_counter.h
  docs/tips/parameter_settings.md
  script/add_section/settings.pl
  script/ci/check_encoding.json
Labels: invalid, priority::high

#129 Drop AA HAL support
  CHANGELOG.md
  build.rs
  hal/aa.h
  hal/mod.rs
Labels: priority::medium

#130 Drop PA HAL support
  CHANGELOG.md
  build.rs
  hal/mod.rs
  hal/pa.h
Labels: priority::medium

#131 Drop SPWIRE HAL support
  CHANGELOG.md
  build.rs
  hal/mod.rs
  hal/spwire.h
Labels: priority::medium

#127 Import README.md as crate documentation
  c2a_core.rs
Labels: documentation, enhancement, priority::low, tools

#132 Refactor user cmake option
  examples/mobc/CMakeLists.txt
  examples/mobc/build.rs
  examples/mobc/src/src_user/hal/CMakeLists.txt
  examples/subobc/CMakeLists.txt
  examples/subobc/build.rs
  examples/subobc/src/src_user/hal/CMakeLists.txt
Labels: enhancement, priority::high, tools

#140 Add missing user_defined application dirname migration
  examples/mobc/src/src_user/applications/user_defined/aocs/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/cdh/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/com/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/mission/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/power/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/prop/.gitkeep
  examples/mobc/src/src_user/applications/user_defined/thermal/.gitkeep
  script/migration/v4-rename-applications.sh
Labels: bug, priority::high

#139 Pre Release (v4.0.0-beta.3): Change C2A_USE_SCI_COM_WINGS default OFF
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
  examples/mobc/CMakeLists.txt
  examples/mobc/src/src_user/Test/README.md
  examples/subobc/CMakeLists.txt
  examples/subobc/src/src_user/Test/README.md
Labels: enhancement, priority::high, S2E, WINGS

#149 Component Driver の rename に伴う微修正
  examples/mobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/mobc/src/src_user/applications/driver_instances/di_aobc.c
  examples/mobc/src/src_user/applications/driver_instances/di_gs.c
  examples/mobc/src/src_user/applications/driver_instances/di_uart_test.c
  examples/mobc/src/src_user/component_driver/aocs/aobc.c
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs.h
  examples/mobc/src/src_user/component_driver/etc/uart_test.c
  examples/subobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/subobc/src/src_user/applications/driver_instances/di_mobc.c
  examples/subobc/src/src_user/component_driver/etc/mobc.c
Labels: priority::high

#143 Rename driver_instances -> component_service
  component_driver/driver_super.h
  docs/component_driver/overview.md
  docs/general/coding_rule.md
  script/migration/v4-rename-driver-instance.sh
Labels: enhancement, priority::high

#144 Apply rename migration: driver_instances -> component_service
  examples/mobc/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_drivers_update.c
  examples/mobc/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_gs_related_process.c
  examples/mobc/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_tlm_cmd_hirate.c
  examples/mobc/src/src_user/Settings/Modes/TaskLists/tl_initial.c
  examples/mobc/src/src_user/Settings/Modes/Transitions/sl_initial.c
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  examples/mobc/src/src_user/applications/CMakeLists.txt
  examples/mobc/src/src_user/applications/app_headers.h
  examples/mobc/src/src_user/applications/app_registry.c
  examples/mobc/src/src_user/applications/app_registry.h
  examples/mobc/src/src_user/applications/component_service/csrv_aobc.c
  examples/mobc/src/src_user/applications/component_service/csrv_aobc.h
  examples/mobc/src/src_user/applications/component_service/csrv_gs.c
  examples/mobc/src/src_user/applications/component_service/csrv_gs.h
  examples/mobc/src/src_user/applications/component_service/csrv_uart_test.c
  examples/mobc/src/src_user/applications/component_service/csrv_uart_test.h
  examples/mobc/src/src_user/applications/driver_instances/di_gs.c
  examples/mobc/src/src_user/applications/driver_instances/di_gs.h
  examples/mobc/src/src_user/applications/user_defined/debug_apps.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/user_packet_handler.c
  examples/subobc/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_gs_related_process.c
  examples/subobc/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_tlm_cmd_hirate.c
  examples/subobc/src/src_user/Settings/tlm_cmd/data_base/CMDFILE/sample.ops
  examples/subobc/src/src_user/Test/test/test_comm_between_c2a.py
  examples/subobc/src/src_user/applications/CMakeLists.txt
  examples/subobc/src/src_user/applications/app_headers.h
  examples/subobc/src/src_user/applications/app_registry.c
  examples/subobc/src/src_user/applications/app_registry.h
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.c
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.h
  examples/subobc/src/src_user/applications/user_defined/debug_apps.c
Labels: enhancement, priority::high

#150 Pre Release (v4.0.0-beta.4): DI → CSRV rename に伴う，手動での user 側微修正
  Cargo.toml
  c2a_core_main.h
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/src/src_user/applications/app_headers.h
  examples/mobc/src/src_user/applications/component_service/csrv_aobc.c
  examples/mobc/src/src_user/applications/component_service/csrv_aobc.h
  examples/mobc/src/src_user/applications/component_service/csrv_uart_test.c
  examples/mobc/src/src_user/applications/component_service/csrv_uart_test.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/subobc/src/src_user/applications/app_headers.h
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.c
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.h
  script/migration/v4-rename-driver-instance.sh
Labels: priority::high

#153 Rename code-generator
  .github/workflows/check_code_generation.yml
  code-generator/.flake8
  code-generator/.gitignore
  code-generator/GenerateC2ACode.py
  code-generator/README.md
  code-generator/my_mod/cmd_def.py
  code-generator/my_mod/load_db.py
  code-generator/my_mod/tlm_buffer.py
  code-generator/my_mod/tlm_def.py
  code-generator/pyproject.toml
  code-generator/requirements.txt
  code-generator/settings_mobc.json
  code-generator/settings_subobc.json
  docs/component_driver/communication_with_components.md
Labels: priority::medium, tools

#138 Refactor user test dir
  .github/workflows/pytest.yml
  README.md
  examples/mobc/src/src_user/test/.python-version
  examples/mobc/src/src_user/test/README.md
  examples/mobc/src/src_user/test/conftest.py
  examples/mobc/src/src_user/test/pyproject.toml
  examples/mobc/src/src_user/test/pytest.ini
  examples/mobc/src/src_user/test/requirements-dev.lock
  examples/mobc/src/src_user/test/requirements.lock
  examples/mobc/src/src_user/test/settings.json
  examples/mobc/src/src_user/test/src_core/applications/test_event_utility.py
  examples/mobc/src/src_user/test/src_core/applications/test_timeline_command_dispatcher.py
  examples/mobc/src/src_user/test/src_core/system/event_manager/test_event_handler.py
  examples/mobc/src/src_user/test/src_core/system/event_manager/test_event_logger.py
  examples/mobc/src/src_user/test/src_core/system/mode_manager/test_mode_manager.py
  examples/mobc/src/src_user/test/src_core/system/task_manager/test_task_dispatcher.py
  examples/mobc/src/src_user/test/src_core/system/time_manager/test_obc_time.py
  examples/mobc/src/src_user/test/src_core/system/time_manager/test_time_manager.py
  examples/mobc/src/src_user/test/src_core/system/watchdog_timer/test_watchdog_timer.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_block_command_loader.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_command_analyze.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_command_dispatcher.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_command_dispatcher_manager.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_common_cmd_packet_util.py
  examples/mobc/src/src_user/test/src_core/tlm_cmd/test_telemetry_frame.py
  examples/mobc/src/src_user/test/src_user/.gitkeep
  examples/mobc/src/src_user/test/utils/c2a_enum_utils.py
  examples/mobc/src/src_user/test/utils/wings_utils.py
  examples/subobc/src/src_user/test/.python-version
  examples/subobc/src/src_user/test/README.md
  examples/subobc/src/src_user/test/conftest.py
  examples/subobc/src/src_user/test/pyproject.toml
  examples/subobc/src/src_user/test/pytest.ini
  examples/subobc/src/src_user/test/requirements-dev.lock
  examples/subobc/src/src_user/test/requirements.lock
  examples/subobc/src/src_user/test/settings.json
  examples/subobc/src/src_user/test/test_comm_between_c2a.py
  examples/subobc/src/src_user/test/utils/c2a_enum_utils.py
  examples/subobc/src/src_user/test/utils/wings_utils.py
  script/migration/v4-rename-test-dir.sh
Labels: priority::high, tools

#154 Rename component driver prefix
  CMakeLists.txt
  code-generator/my_mod/tlm_buffer.py
  component_driver/cdrv_common_tlm_cmd_packet.c
  component_driver/cdrv_common_tlm_cmd_packet.h
  component_driver/cdrv_eb90_frame.c
  component_driver/cdrv_eb90_frame.h
  component_driver/cdrv_eb90_packet.c
  component_driver/cdrv_eb90_packet.h
  component_driver/eb90_frame_for_driver_super.c
  component_driver/eb90_packet_for_driver_super.c
  script/migration/v4-rename-component-driver-prefix.sh
Labels: priority::high, tools

#155 Apply rename migration: component driver prefix
  examples/mobc/src/src_user/component_driver/aocs/aobc.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/subobc/src/src_user/component_driver/etc/mobc.c
Labels: priority::high, tools

#165 Rename & Refactor IF list to CDS handler registry
  component_driver/driver_super.c
  component_driver/driver_super.h
  script/migration/v4-rename-if-list.sh
Labels: priority::high

#166 Apply rename migration: IF list
  examples/mobc/src/src_user/Settings/CMakeLists.txt
  examples/mobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/mobc/src/src_user/Settings/component_driver_super/driver_super_params.h
  examples/mobc/src/src_user/Settings/component_driver_super/hal_handler_registry.c
  examples/mobc/src/src_user/Settings/component_driver_super/hal_handler_registry.h
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  examples/mobc/src/src_user/Settings/tlm_cmd/data_base/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  examples/mobc/src/src_user/component_driver/aocs/aobc.c
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs.h
  examples/mobc/src/src_user/component_driver/etc/uart_test.c
  examples/mobc/src/src_user/hal/CMakeLists.txt
  examples/mobc/src/src_user/hal/if_list.c
  examples/mobc/src/src_user/hal/if_list.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/subobc/src/src_user/Settings/CMakeLists.txt
  examples/subobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/subobc/src/src_user/Settings/component_driver_super/hal_handler_registry.c
  examples/subobc/src/src_user/Settings/component_driver_super/hal_handler_registry.h
  examples/subobc/src/src_user/component_driver/etc/mobc.c
  examples/subobc/src/src_user/hal/CMakeLists.txt
  examples/subobc/src/src_user/hal/if_list.c
  examples/subobc/src/src_user/hal/if_list.h
Labels: priority::high

#169 Pre Release (v4.0.0-beta.5): フォーマット微修正 / 変数名修正
  Cargo.toml
  c2a_core_main.h
  component_driver/driver_super.c
  component_driver/driver_super.h
  examples/mobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/mobc/src/src_user/Settings/component_driver_super/driver_super_params.h
  examples/mobc/src/src_user/Settings/component_driver_super/hal_handler_registry.c
  examples/mobc/src/src_user/Settings/component_driver_super/hal_handler_registry.h
  examples/mobc/src/src_user/component_driver/aocs/aobc.c
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs.h
  examples/mobc/src/src_user/component_driver/etc/uart_test.c
  examples/subobc/src/src_user/Settings/component_driver_super/driver_buffer_define.h
  examples/subobc/src/src_user/Settings/component_driver_super/hal_handler_registry.c
  examples/subobc/src/src_user/Settings/component_driver_super/hal_handler_registry.h
  examples/subobc/src/src_user/component_driver/etc/mobc.c
Labels: priority::low

#167 Rename user Settings dir
  applications/divided_cmd_utility.h
  applications/telemetry_manager.c
  applications/telemetry_manager.h
  applications/timeline_command_dispatcher_id_define.h
  applications/utility_command.c
  applications/utility_counter.h
  code-generator/settings_mobc.json
  code-generator/settings_subobc.json
  component_driver/driver_super.h
  docs/general/coding_rule.md
  docs/tips/parameter_settings.md
  library/endian.c
  library/git_revision.h
  library/print.h
  script/git_hooks/pre-commit
  script/migration/v4-rename-settings.sh
  system/application_manager/app_manager.c
  system/application_manager/app_manager.h
  system/event_manager/event_handler.h
  system/event_manager/event_logger.c
  system/event_manager/event_logger.h
  system/mode_manager/mode_manager.h
  system/task_manager/task_dispatcher.h
  system/time_manager/obc_time_config.h
  tlm_cmd/block_command_table.h
  tlm_cmd/ccsds/cmd_space_packet.h
  tlm_cmd/ccsds/space_packet_typedef.h
  tlm_cmd/ccsds/tlm_space_packet.h
  tlm_cmd/command_analyze.h
  tlm_cmd/command_dispatcher_manager.h
  tlm_cmd/common_cmd_packet.h
  tlm_cmd/common_tlm_cmd_packet.h
  tlm_cmd/common_tlm_packet.h
  tlm_cmd/packet_handler.h
  tlm_cmd/telemetry_frame.h
  tlm_cmd/telemetry_generator.c
Labels: priority::high

#173 Fix missing rename/drop in scripts
  examples/subobc/sync_with_mobc_example.bat
  script/git_hooks/pre-commit
Labels: bug, priority::medium
