Repository arkedge/c2a-core, pull requests merged in 2023-11, with the labels that each got.

#157 Update v4 changelog
  CHANGELOG.md
Labels: documentation, priority::high

#177 インデントのスペースを GFM に準拠する
  docs/README.md
  docs/application/overview.md
  docs/component_driver/communication_with_components.md
  docs/component_driver/overview.md
  docs/core/communication.md
  docs/core/tips.md
  docs/general/coding_rule.md
  docs/general/release.md
  docs/tips/parameter_settings.md
  examples/mobc/src/src_user/hal/sils_mockup/README.md
  examples/mobc/src/src_user/test/README.md
  examples/subobc/src/src_user/hal/sils_mockup/README.md
  examples/subobc/src/src_user/test/README.md
Labels: documentation, priority::high

#174 Update version (v4.0.0)
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
Labels: enhancement, priority::high

#180 Refactor v4 IfWrapper migration script
  script/migration/v4-rename-ifwrapper.sh
Labels: priority::high, tools

#182 Refactor v4 migration script
  script/migration/v4-move-db-dir.sh
  script/migration/v4-rename-applications.sh
  script/migration/v4-rename-component-driver-prefix.sh
  script/migration/v4-rename-driver-instance.sh
  script/migration/v4-rename-driver.sh
  script/migration/v4-rename-driver2.sh
  script/migration/v4-rename-if-list.sh
  script/migration/v4-rename-library.sh
  script/migration/v4-rename-script.sh
  script/migration/v4-rename-settings.sh
  script/migration/v4-rename-system.sh
  script/migration/v4-rename-tlmcmd.sh
Labels: priority::high, tools

#185 add Gaia label
  .github/labels.yml
Labels: priority::medium, tools

#183 Update version (v4.0.1)
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
Labels: priority::high, tools

#200 Update main (v4.0.1) on 2023-11-09
  .github/labels.yml
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
  script/migration/v4-move-db-dir.sh
  script/migration/v4-rename-applications.sh
  script/migration/v4-rename-component-driver-prefix.sh
  script/migration/v4-rename-driver-instance.sh
  script/migration/v4-rename-driver.sh
  script/migration/v4-rename-driver2.sh
  script/migration/v4-rename-if-list.sh
  script/migration/v4-rename-ifwrapper.sh
  script/migration/v4-rename-library.sh
  script/migration/v4-rename-script.sh
  script/migration/v4-rename-settings.sh
  script/migration/v4-rename-system.sh
  script/migration/v4-rename-tlmcmd.sh
Labels: priority::high, tools

#188 [v3.10.1 Backport] PL_BC_LIST_CLEARED を level high で EL 登録する
  applications/timeline_command_dispatcher.c
Labels: priority::medium

#193 VCDU を AOS transfer frame に rename する
  CHANGELOG.md
  applications/memory_dump.c
  examples/mobc/src/src_user/applications/component_service/csrv_gs.c
  examples/mobc/src/src_user/applications/component_service/csrv_gs.h
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs.h
  examples/mobc/src/src_user/tlm_cmd/CMakeLists.txt
  examples/mobc/src/src_user/tlm_cmd/ccsds/aos_transfer_frame.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/aos_transfer_frame.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/m_pdu.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/tcp_to_m_pdu.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/vcdu.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/vcdu.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  tlm_cmd/ccsds/space_packet_typedef.h
  tlm_cmd/telemetry_generator.c
Labels: priority::high

#197 M_PDU をコード規約に合わせるなどのリファクタ
  CHANGELOG.md
  examples/mobc/src/src_user/tlm_cmd/CMakeLists.txt
  examples/mobc/src/src_user/tlm_cmd/ccsds/aos_transfer_frame.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/m_pdu.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/multiplexing_protocol_data_unit.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/multiplexing_protocol_data_unit.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/tcp_to_m_pdu.c
  examples/mobc/src/src_user/tlm_cmd/ccsds/tcp_to_m_pdu.h
Labels: priority::medium

#204 More match script migration
  script/migration/v4-rename-script.sh
Labels: bug, priority::high, tools

#205 Fix v4 applications rename order
  script/migration/v4-rename-applications.sh
Labels: bug, priority::high, tools

#206 More match system migration
  script/migration/v4-rename-system.sh
Labels: bug, priority::high, tools

#199 Drop c2a-core crate links config
  Cargo.toml
  build.rs
Labels: priority::high, tools

#211 Fix v4 system rename typo
  script/migration/v4-rename-system.sh
Labels: priority::high, tools

#201 Refactor release rule
  docs/general/release.md
Labels: documentation, enhancement, priority::high

#215 Update v4.0.0 migration guide
  CHANGELOG.md
Labels: documentation

#218 Feedback from v4.0.0 beta.4
  CHANGELOG.md
  script/migration/v4-rename-driver2.sh
Labels: documentation, priority::medium, tools

#207 Move doxygen config to top
  .gitignore
  Doxyfile
Labels: documentation, priority::medium

#208 Exclude Doxygen stdint_wrapper
  Doxyfile
Labels: documentation, priority::low

#223 Feedback from v4.0.0 beta.5 migration
  script/migration/v4-rename-component-driver-prefix.sh
  script/migration/v4-rename-if-list.sh
  script/migration/v4-rename-test-dir.sh
Labels: priority::high, tools

#224 Feedback from v4.0.0 migration
  CHANGELOG.md
  script/migration/v4-rename-settings.sh
Labels: documentation, priority::medium, tools

#222 add section 漏れを修正
  CHANGELOG.md
  library/endian.c
  library/libc/bsearch.c
  library/libc/memchr.c
Labels: bug, priority::high

#225 Space Packet 関連ファイルのディレクトリを変更
  CHANGELOG.md
  CMakeLists.txt
  examples/mobc/src/src_user/component_driver/com/gs.c
  examples/mobc/src/src_user/component_driver/com/gs_validate.c
  examples/mobc/src/src_user/settings/tlm_cmd/common_cmd_packet_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_cmd_packet_define.h
  examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/tc_segment.h
  examples/mobc/src/src_user/tlm_cmd/ccsds/tcp_to_m_pdu.c
  examples/mobc/src/src_user/tlm_cmd/common_cmd_packet.c
  examples/mobc/src/src_user/tlm_cmd/common_tlm_cmd_packet.c
  examples/mobc/src/src_user/tlm_cmd/common_tlm_packet.c
  examples/subobc/src/src_user/settings/tlm_cmd/common_cmd_packet_define.h
  examples/subobc/src/src_user/settings/tlm_cmd/common_tlm_cmd_packet_define.h
  examples/subobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.h
  examples/subobc/src/src_user/tlm_cmd/common_cmd_packet.c
  examples/subobc/src/src_user/tlm_cmd/common_tlm_cmd_packet.c
  examples/subobc/src/src_user/tlm_cmd/common_tlm_packet.c
  tlm_cmd/block_command_table.c
  tlm_cmd/ccsds/space_packet_protocol/cmd_space_packet.c
  tlm_cmd/ccsds/space_packet_protocol/cmd_space_packet.h
  tlm_cmd/ccsds/space_packet_protocol/space_packet.c
  tlm_cmd/ccsds/space_packet_protocol/space_packet.h
  tlm_cmd/ccsds/space_packet_protocol/space_packet_typedef.h
  tlm_cmd/ccsds/space_packet_protocol/tlm_space_packet.c
  tlm_cmd/ccsds/space_packet_protocol/tlm_space_packet.h
  tlm_cmd/telemetry_generator.c
Labels: priority::high
