Repository arkedge/c2a-core, pull requests merged in 2024-04, with the labels that each got.

#330 Rename c2a-sils-runtime to c2a-dev-runtime
  Cargo.toml
  README.md
  dev-runtime/Cargo.toml
  dev-runtime/src/lib.rs
  docs/README.md
  docs/sils/c2a_dev_runtime.md
  examples/mobc/Cargo.toml
  examples/mobc/src/main.rs
  examples/mobc/src/src_user/test/README.md
  examples/subobc/Cargo.toml
  examples/subobc/src/main.rs
Labels: enhancement

#329 Common Packet のデフォルト実装を core から提供する（Space Packet のみ）
  CMakeLists.txt
  examples/mobc/CMakeLists.txt
  examples/mobc/src/src_user/settings/CMakeLists.txt
  examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
  examples/mobc/src/src_user/tlm_cmd/CMakeLists.txt
  examples/mobc/src/src_user/tlm_cmd/common_tlm_packet.c
  examples/subobc/src/src_user/settings/CMakeLists.txt
  examples/subobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
  examples/subobc/src/src_user/tlm_cmd/CMakeLists.txt
  examples/subobc/src/src_user/tlm_cmd/common_cmd_packet.c
  examples/subobc/src/src_user/tlm_cmd/common_tlm_cmd_packet.c
  examples/subobc/sync_with_mobc_example.bat
  tlm_cmd/common_packet/space_packet/CMakeLists.txt
  tlm_cmd/common_packet/space_packet/common_cmd_packet.c
  tlm_cmd/common_packet/space_packet/common_tlm_cmd_packet.c
  tlm_cmd/common_packet/space_packet/common_tlm_packet.c
Labels: enhancement, priority::high

#331 Example user CMake config is not only for SILS-S2E
  examples/mobc/CMakeLists.txt
  examples/subobc/CMakeLists.txt
Labels: documentation, invalid, tools

#328 C2A User 開発者のための簡易なドキュメントを追加
  CMakeLists.txt
  docs/README.md
  docs/application/overview.md
  docs/core/ccsds.md
  docs/core/communication.md
  docs/general/architecture.md
  docs/general/cmake.md
Labels: documentation
