Repository arkedge/c2a-core, pull requests merged in 2024-05, with the labels that each got.

#343 Update version (v4.4.0)
  Cargo.toml
  c2a_core_main.h
Labels: priority::medium

#344 bindgen C2A RESULT type
  build.rs
  c2a_core.rs
  library/mod.rs
Labels: enhancement

#345 Tell c2a-core crate re-build condition to cargo
  build.rs
Labels: priority::low, tools
