Repository arkedge/c2a-core, pull requests merged in 2024-01, with the labels that each got.

#265 [code-generator] subobc の MD5 の計算のバグ修正
  CHANGELOG.md
  code-generator/my_mod/util.py
  examples/mobc/src/src_user/component_driver/aocs/aobc_command_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.c
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_buffer.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_data_definitions.h
  examples/mobc/src/src_user/component_driver/aocs/aobc_telemetry_definitions.h
Labels: bug, priority::high, tools

#266 core tlm の tlm id を再採番する (CDIS, CA)
  CHANGELOG.md
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_CDIS.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CDIS.csv
Labels: documentation, priority::medium

#263 CDIS や BCT に保存された CCP をダンプする App を追加
  CHANGELOG.md
  applications/CMakeLists.txt
  applications/ccp_dump.c
  applications/ccp_dump.h
  examples/mobc/src/src_user/applications/app_headers.h
  examples/mobc/src/src_user/applications/app_registry.c
  examples/mobc/src/src_user/applications/app_registry.h
  examples/mobc/src/src_user/test/src_core/applications/test_ccp_dump.py
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_CCP_DUMP.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CCP_DUMP.csv
  tlm_cmd/command_dispatcher_manager.c
  tlm_cmd/command_dispatcher_manager.h
  tlm_cmd/packet_list.c
  tlm_cmd/packet_list.h
Labels: enhancement, priority::medium

#278 タスク定期実行に関するドキュメントを追加
  docs/README.md
  docs/application/scheduled_task_execution.md
Labels: documentation, priority::low

#269 Rename `src_user/settings/component_driver_super/` dir to `src_user/settings/component_driver/` dir
  CHANGELOG.md
  component_driver/driver_super.h
  examples/mobc/src/src_user/applications/component_service/csrv_aobc.c
  examples/mobc/src/src_user/applications/component_service/csrv_gs.c
  examples/mobc/src/src_user/applications/component_service/csrv_uart_test.c
  examples/mobc/src/src_user/settings/CMakeLists.txt
  examples/mobc/src/src_user/settings/component_driver/driver_buffer_define.h
  examples/mobc/src/src_user/settings/component_driver/driver_super_params.h
  examples/mobc/src/src_user/settings/component_driver/hal_handler_registry.c
  examples/mobc/src/src_user/settings/component_driver/hal_handler_registry.h
  examples/subobc/src/src_user/applications/component_service/csrv_mobc.c
  examples/subobc/src/src_user/settings/CMakeLists.txt
  examples/subobc/src/src_user/settings/component_driver/driver_buffer_define.h
  examples/subobc/src/src_user/settings/component_driver/driver_super_params.h
  examples/subobc/src/src_user/settings/component_driver/hal_handler_registry.c
  examples/subobc/src/src_user/settings/component_driver/hal_handler_registry.h
Labels: priority::medium

#271 CDS: ComponentDriverSuper の整理（コードに変更なし）
  CHANGELOG.md
  component_driver/driver_super.c
  component_driver/driver_super.h
Labels: priority::medium

#270 Component Driver を統一的に c2a-core で扱えるようにし，CDS の tlm と，テレメ不通関連 Cmd を追加
  CHANGELOG.md
  CMakeLists.txt
  applications/CMakeLists.txt
  applications/component_driver_utility.c
  applications/component_driver_utility.h
  component_driver/component_driver.c
  component_driver/component_driver.h
  examples/mobc/src/src_user/applications/app_headers.h
  examples/mobc/src/src_user/applications/app_registry.c
  examples/mobc/src/src_user/applications/app_registry.h
  examples/mobc/src/src_user/settings/CMakeLists.txt
  examples/mobc/src/src_user/settings/component_driver/component_driver_define.c
  examples/mobc/src/src_user/settings/component_driver/component_driver_define.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_CDRV_UTIL.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CDRV_UTIL.csv
  examples/subobc/src/src_user/settings/CMakeLists.txt
  examples/subobc/src/src_user/settings/component_driver/component_driver_define.c
  examples/subobc/src/src_user/settings/component_driver/component_driver_define.h
Labels: enhancement, priority::medium

#272 sync_with_mobc_example.bat のメンテ
  CHANGELOG.md
  examples/subobc/src/src_user/settings/tlm_cmd/ccsds/apid_define.h
  examples/subobc/sync_with_mobc_example.bat
Labels: priority::medium, tools

#273 任意の Component Driver に対して，任意バイト列の送受信と HAL init, reopen Cmd を提供する
  CHANGELOG.md
  applications/component_driver_utility.c
  applications/component_driver_utility.h
  component_driver/driver_super.c
  component_driver/driver_super.h
  examples/mobc/src/src_user/settings/applications/component_driver_utility_params.h
  examples/mobc/src/src_user/test/src_core/applications/test_component_driver_utility.py
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_CDRV_UTIL_HAL_RX_DATA.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CDRV_UTIL_HAL_RX_DATA.csv
  examples/subobc/src/src_user/test/test/test_comm_between_c2a.py
  examples/subobc/src/src_user/test/test/test_component_driver_utility.py
  hal/ccsds.h
  hal/i2c.h
  hal/spi.h
  hal/uart.h
Labels: enhancement, priority::medium

#274 `TMGR_get_master_mode_cycle_in_msec` などの in_sec 版を実装
  CHANGELOG.md
  system/time_manager/time_manager.c
  system/time_manager/time_manager.h
Labels: enhancement, priority::medium

#275 AM tlm で不用意にサイズを切り詰めたキャストを緩和し，初期化時間や実行時間の長い App の時間を正確に知れるように
  CHANGELOG.md
  examples/mobc/src/src_user/settings/system/app_manager_params.h
  examples/mobc/src/src_user/tlm_cmd/block_command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/command_definitions.c
  examples/mobc/src/src_user/tlm_cmd/command_definitions.h
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.c
  examples/mobc/src/src_user/tlm_cmd/telemetry_definitions.h
  examples/mobc/tlm-cmd-db/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  examples/mobc/tlm-cmd-db/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_AM.csv
  system/application_manager/app_manager.h
Labels: enhancement, priority::medium

#260 C2A 初期化時に実行環境のエンディアンが設定と正しいかチェックする
  CHANGELOG.md
  c2a_core_main.c
  library/endian.c
  library/endian.h
Labels: enhancement, priority::medium

#279 component_driver_utility.c でのパラメタ取得のバグ修正
  CHANGELOG.md
  applications/component_driver_utility.c
Labels: bug

#281 Use Gaia 0.6 in C2A Boom for C2A DevTools usage update
  docs/development/development_environment.md
  docs/sils/c2a_sils_runtime.md
  examples/mobc/tools/install.sh
  examples/subobc/tools/install.sh
Labels: documentation, enhancement, priority::high, tools, Gaia

#283 Fix check-coding-rule v4 workflow in workflows-c2a v5
  .github/workflows/check_coding_rule.yml
Labels: bug, priority::high, tools

#284 Enable example build all again
  .github/workflows/build.yml
Labels: enhancement, priority::high, tools

#285 Use matrix job to build multiple example users with same config
  .github/workflows/build.yml
Labels: priority::medium, tools

#286 Fix examples/subobc pytest testcase dir
  CHANGELOG.md
  examples/mobc/src/src_user/test/src_core/applications/test_component_driver_utility.py
  examples/subobc/src/src_user/test/test_comm_between_c2a.py
  examples/subobc/src/src_user/test/test_component_driver_utility.py
Labels: invalid, priority::high, tools

#298 [code_fenerator] max_tlm_num のアサーションの off-by-one error の修正
  code-generator/my_mod/load_db.py
Labels: bug, priority::high

#287 Update version (v4.2.0)
  CHANGELOG.md
  Cargo.toml
  c2a_core_main.h
Labels: documentation, priority::high
