Repository arkedge/c2a-core, pull requests merged in 2025-01, with the labels that each got.

#406 Add c2a-core Cargo lockfile
  .gitignore
  Cargo.lock
Labels: enhancement, priority::medium, tools

#395 Update C2A heritage (ONGLAISAT / YODAKA)
  README.md
Labels: documentation

#400 Fix link in c2a_dev_runtime.md
  docs/sils/c2a_dev_runtime.md
Labels: documentation

#399 chore: add repository to bind-utils package metadata
  Cargo.toml
  library/bind-utils/Cargo.toml
Labels: priority::low
